# Generated by Django 5.1.4 on 2024-12-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_delivery_delivery_person_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.hostel'),
        ),
    ]
