# Generated by Django 5.1.4 on 2024-12-27 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_team'),
        ('user_management', '0003_profile_assigned_hostel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='hostel',
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_management_team_set', to='restaurant.all_orders'),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_management_team_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='assigned_hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_management_team_set', to='user_management.hostel'),
        ),
    ]
