# Generated by Django 5.1.4 on 2025-01-04 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_restaurant_user_restaurant_description_and_more'),
        ('user_management', '0004_remove_delivery_hostel_team_order_team_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_set', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='team',
            name='assigned_hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_set', to='user_management.hostel'),
        ),
        migrations.AlterField(
            model_name='team',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_set', to='restaurant.all_orders'),
        ),
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
