# Generated by Django 5.1.4 on 2024-12-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_orders',
            name='block_number',
            field=models.CharField(blank=True, default='Unknown Block', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='all_orders',
            name='hostel_name',
            field=models.CharField(default='Unknown Hostel', max_length=100),
        ),
        migrations.AddField(
            model_name='all_orders',
            name='room_number',
            field=models.CharField(default='Unknown Room', max_length=100),
        ),
        migrations.AddField(
            model_name='payments',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='mpesa_transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
