# Generated by Django 5.1.4 on 2024-12-27 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_all_orders_block_number_all_orders_hostel_name_and_more'),
        ('user_management', '0003_profile_assigned_hostel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='images/')),
                ('occupation', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete')], default='pending', max_length=10)),
                ('assigned_hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_team_set', to='user_management.hostel')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_team_set', to='restaurant.all_orders')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_team_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
