# Generated by Django 5.1.4 on 2024-12-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_orders',
            name='delivery_address',
        ),
    ]
