# Generated by Django 5.1.4 on 2024-12-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_remove_all_orders_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='delivery_code',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='order_no',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='transaction_id',
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
