# Generated by Django 5.1.4 on 2025-01-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_orderitems_delivery_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Carts'},
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='total',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurantorderview',
            name='ordered_products',
        ),
        migrations.AddField(
            model_name='restaurantorderview',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='all_orders',
            name='block_number',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='all_orders',
            name='hostel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='all_orders',
            name='order_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='all_orders',
            name='room_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='all_orders',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
