# Generated by Django 5.1.4 on 2025-01-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_cart_options_remove_orderitems_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='Default location', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_pictures/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
