# Generated by Django 5.1.4 on 2025-01-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_restaurant_user_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_orders',
            name='delivery_status',
            field=models.CharField(choices=[('picked', 'Picked'), ('packed', 'Packed'), ('on_transit', 'On Transit'), ('complete', 'Complete')], default='picked', max_length=20),
        ),
        migrations.AddField(
            model_name='all_orders',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='all_orders',
            name='order_no',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
