# Generated by Django 5.1.4 on 2025-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_all_orders_delivery_status_all_orders_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
